version: release

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /home/ans/foundry-vtt/foundrydata
        target: /data
    environment:
      - FOUNDRY_PASSWORD=5(=$!P^fqO4i
      - FOUNDRY_USERNAME=Dungeon_Mastermind
      - FOUNDRY_ADMIN_KEY=P9KQ-LA6Q-N2FC-L2QE-2KCQ-OGEC
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
